// Generated by gencpp from file tgr_msgs/MotorVal.msg
// DO NOT EDIT!


#ifndef TGR_MSGS_MESSAGE_MOTORVAL_H
#define TGR_MSGS_MESSAGE_MOTORVAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tgr_msgs
{
template <class ContainerAllocator>
struct MotorVal_
{
  typedef MotorVal_<ContainerAllocator> Type;

  MotorVal_()
    : right_wheel(0.0)
    , left_wheel(0.0)  {
    }
  MotorVal_(const ContainerAllocator& _alloc)
    : right_wheel(0.0)
    , left_wheel(0.0)  {
  (void)_alloc;
    }



   typedef double _right_wheel_type;
  _right_wheel_type right_wheel;

   typedef double _left_wheel_type;
  _left_wheel_type left_wheel;





  typedef boost::shared_ptr< ::tgr_msgs::MotorVal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tgr_msgs::MotorVal_<ContainerAllocator> const> ConstPtr;

}; // struct MotorVal_

typedef ::tgr_msgs::MotorVal_<std::allocator<void> > MotorVal;

typedef boost::shared_ptr< ::tgr_msgs::MotorVal > MotorValPtr;
typedef boost::shared_ptr< ::tgr_msgs::MotorVal const> MotorValConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tgr_msgs::MotorVal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tgr_msgs::MotorVal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tgr_msgs::MotorVal_<ContainerAllocator1> & lhs, const ::tgr_msgs::MotorVal_<ContainerAllocator2> & rhs)
{
  return lhs.right_wheel == rhs.right_wheel &&
    lhs.left_wheel == rhs.left_wheel;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tgr_msgs::MotorVal_<ContainerAllocator1> & lhs, const ::tgr_msgs::MotorVal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tgr_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tgr_msgs::MotorVal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tgr_msgs::MotorVal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tgr_msgs::MotorVal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tgr_msgs::MotorVal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tgr_msgs::MotorVal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tgr_msgs::MotorVal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tgr_msgs::MotorVal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0140256f3024b29a22db1f900fae1463";
  }

  static const char* value(const ::tgr_msgs::MotorVal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0140256f3024b29aULL;
  static const uint64_t static_value2 = 0x22db1f900fae1463ULL;
};

template<class ContainerAllocator>
struct DataType< ::tgr_msgs::MotorVal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tgr_msgs/MotorVal";
  }

  static const char* value(const ::tgr_msgs::MotorVal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tgr_msgs::MotorVal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 right_wheel\n"
"float64 left_wheel\n"
;
  }

  static const char* value(const ::tgr_msgs::MotorVal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tgr_msgs::MotorVal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.right_wheel);
      stream.next(m.left_wheel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorVal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tgr_msgs::MotorVal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tgr_msgs::MotorVal_<ContainerAllocator>& v)
  {
    s << indent << "right_wheel: ";
    Printer<double>::stream(s, indent + "  ", v.right_wheel);
    s << indent << "left_wheel: ";
    Printer<double>::stream(s, indent + "  ", v.left_wheel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TGR_MSGS_MESSAGE_MOTORVAL_H
