(cl:in-package tgr_msgs-msg)
(cl:export '(VERTICAL_RESOLUTION-VAL
          VERTICAL_RESOLUTION
          HORIZONTAL_RESOLUTION-VAL
          HORIZONTAL_RESOLUTION
          VERTICAL_FOV-VAL
          VERTICAL_FOV
          HORIZONTAL_FOV-VAL
          HORIZONTAL_FOV
          CAMERA_POSITION-VAL
          CAMERA_POSITION
          CAMERA_ORIENTATION-VAL
          CAMERA_ORIENTATION
))