# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from tgr_msgs/CameraSpecs.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class CameraSpecs(genpy.Message):
  _md5sum = "68b9d8e8fe95a0178aa4b8e3061de049"
  _type = "tgr_msgs/CameraSpecs"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 vertical_resolution
int32 horizontal_resolution
float64 vertical_fov
float64 horizontal_fov
geometry_msgs/Point camera_position
geometry_msgs/Point camera_orientation
================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['vertical_resolution','horizontal_resolution','vertical_fov','horizontal_fov','camera_position','camera_orientation']
  _slot_types = ['int32','int32','float64','float64','geometry_msgs/Point','geometry_msgs/Point']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       vertical_resolution,horizontal_resolution,vertical_fov,horizontal_fov,camera_position,camera_orientation

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CameraSpecs, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.vertical_resolution is None:
        self.vertical_resolution = 0
      if self.horizontal_resolution is None:
        self.horizontal_resolution = 0
      if self.vertical_fov is None:
        self.vertical_fov = 0.
      if self.horizontal_fov is None:
        self.horizontal_fov = 0.
      if self.camera_position is None:
        self.camera_position = geometry_msgs.msg.Point()
      if self.camera_orientation is None:
        self.camera_orientation = geometry_msgs.msg.Point()
    else:
      self.vertical_resolution = 0
      self.horizontal_resolution = 0
      self.vertical_fov = 0.
      self.horizontal_fov = 0.
      self.camera_position = geometry_msgs.msg.Point()
      self.camera_orientation = geometry_msgs.msg.Point()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2i8d().pack(_x.vertical_resolution, _x.horizontal_resolution, _x.vertical_fov, _x.horizontal_fov, _x.camera_position.x, _x.camera_position.y, _x.camera_position.z, _x.camera_orientation.x, _x.camera_orientation.y, _x.camera_orientation.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.camera_position is None:
        self.camera_position = geometry_msgs.msg.Point()
      if self.camera_orientation is None:
        self.camera_orientation = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 72
      (_x.vertical_resolution, _x.horizontal_resolution, _x.vertical_fov, _x.horizontal_fov, _x.camera_position.x, _x.camera_position.y, _x.camera_position.z, _x.camera_orientation.x, _x.camera_orientation.y, _x.camera_orientation.z,) = _get_struct_2i8d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2i8d().pack(_x.vertical_resolution, _x.horizontal_resolution, _x.vertical_fov, _x.horizontal_fov, _x.camera_position.x, _x.camera_position.y, _x.camera_position.z, _x.camera_orientation.x, _x.camera_orientation.y, _x.camera_orientation.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.camera_position is None:
        self.camera_position = geometry_msgs.msg.Point()
      if self.camera_orientation is None:
        self.camera_orientation = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 72
      (_x.vertical_resolution, _x.horizontal_resolution, _x.vertical_fov, _x.horizontal_fov, _x.camera_position.x, _x.camera_position.y, _x.camera_position.z, _x.camera_orientation.x, _x.camera_orientation.y, _x.camera_orientation.z,) = _get_struct_2i8d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2i8d = None
def _get_struct_2i8d():
    global _struct_2i8d
    if _struct_2i8d is None:
        _struct_2i8d = struct.Struct("<2i8d")
    return _struct_2i8d
