# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from tgr_msgs/PixelPoses.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import tgr_msgs.msg

class PixelPoses(genpy.Message):
  _md5sum = "4bca10ae68cd3b2be52f35ffecd1a4b4"
  _type = "tgr_msgs/PixelPoses"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """tgr_msgs/PixelPose pixel_0
tgr_msgs/PixelPose pixel_1
tgr_msgs/PixelPose pixel_2
================================================================================
MSG: tgr_msgs/PixelPose
int32 vertical
int32 horizontal"""
  __slots__ = ['pixel_0','pixel_1','pixel_2']
  _slot_types = ['tgr_msgs/PixelPose','tgr_msgs/PixelPose','tgr_msgs/PixelPose']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       pixel_0,pixel_1,pixel_2

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PixelPoses, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.pixel_0 is None:
        self.pixel_0 = tgr_msgs.msg.PixelPose()
      if self.pixel_1 is None:
        self.pixel_1 = tgr_msgs.msg.PixelPose()
      if self.pixel_2 is None:
        self.pixel_2 = tgr_msgs.msg.PixelPose()
    else:
      self.pixel_0 = tgr_msgs.msg.PixelPose()
      self.pixel_1 = tgr_msgs.msg.PixelPose()
      self.pixel_2 = tgr_msgs.msg.PixelPose()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6i().pack(_x.pixel_0.vertical, _x.pixel_0.horizontal, _x.pixel_1.vertical, _x.pixel_1.horizontal, _x.pixel_2.vertical, _x.pixel_2.horizontal))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pixel_0 is None:
        self.pixel_0 = tgr_msgs.msg.PixelPose()
      if self.pixel_1 is None:
        self.pixel_1 = tgr_msgs.msg.PixelPose()
      if self.pixel_2 is None:
        self.pixel_2 = tgr_msgs.msg.PixelPose()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.pixel_0.vertical, _x.pixel_0.horizontal, _x.pixel_1.vertical, _x.pixel_1.horizontal, _x.pixel_2.vertical, _x.pixel_2.horizontal,) = _get_struct_6i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6i().pack(_x.pixel_0.vertical, _x.pixel_0.horizontal, _x.pixel_1.vertical, _x.pixel_1.horizontal, _x.pixel_2.vertical, _x.pixel_2.horizontal))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pixel_0 is None:
        self.pixel_0 = tgr_msgs.msg.PixelPose()
      if self.pixel_1 is None:
        self.pixel_1 = tgr_msgs.msg.PixelPose()
      if self.pixel_2 is None:
        self.pixel_2 = tgr_msgs.msg.PixelPose()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.pixel_0.vertical, _x.pixel_0.horizontal, _x.pixel_1.vertical, _x.pixel_1.horizontal, _x.pixel_2.vertical, _x.pixel_2.horizontal,) = _get_struct_6i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6i = None
def _get_struct_6i():
    global _struct_6i
    if _struct_6i is None:
        _struct_6i = struct.Struct("<6i")
    return _struct_6i
