controller_list:
  - name: fake_pr_robot_controller
    joints:
      - joint1_base_link_to_link1
      - joint2_link1_to_link2
  - name: fake_hand_controller
    joints:
      []
initial:  # Define initial robot poses.
  - group: pr_robot
    pose: naturalpose